services:
  redis-token:
    container_name: redis-token
    image: redis:alpine3.22
    shm_size: 256mb
    restart: unless-stopped
    networks:
      - redis_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 10s
      interval: 10s
      retries: 5
      timeout: 5s

  redis-verification:
    container_name: redis-verification
    image: redis:alpine3.22
    shm_size: 256mb
    restart: unless-stopped
    networks:
      - redis_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 10s
      interval: 10s
      retries: 5
      timeout: 5s

  postgres:
    container_name: postgres
    image: postgres:18.0-alpine3.22
    shm_size: 128mb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U ${DB_USER}"]
      start_period: 5s
      interval: 10s
      retries: 5
      
  migrations:
    container_name: database-migrations
    image: kukymbr/goose-docker:3.26.0
    environment:
      - GOOSE_DRIVER=${DB_DRIVER}
      - GOOSE_DBSTRING=host=${DB_HOST} port=${DB_PORT} user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/backend/migrations:/migrations  
    networks:
      - postgres_network
  
  backend:
    container_name: backend
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
        # Redis Token
      - REDIS_TOKEN_HOST
      - REDIS_TOKEN_PORT
      - REDIS_TOKEN_PASSWORD
      - REDIS_TOKEN_DB
      - REDIS_TOKEN_PROTOCOL
        # Redis Verification
      - REDIS_VERIFICATION_HOST
      - REDIS_VERIFICATION_PORT
      - REDIS_VERIFICATION_PASSWORD
      - REDIS_VERIFICATION_DB
      - REDIS_VERIFICATION_PROTOCOL
        # Database
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_SSL_MODE
        # Service
      - SERVICE_ENV
      - SERVICE_NAME
        # Server
      - SERVER_HOST
      - SERVER_PORT
        # SQL
      - SQL_PATH
        # JWT
      - JWT_SECRET
    depends_on:
      redis-token:
        condition: service_healthy
      redis-verification:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - postgres_network
      - redis_network
      - app_network
  
  frontend:
    container_name: frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network


networks:
  redis_network:
    driver: bridge
  postgres_network:
    driver: bridge
  app_network:
    driver: bridge