service:
  env: prod
  name: auth-service
database:
  host: postgres
  port: 5432
  user: auth_service_user
  password: auth_service_password
  name: auth_service_db 
  ssl_mode: disabled
redis-token:
  host: redis-token
  port: 6379
  password: 12345
  db: 0
  protocol: 3
redis-verification:
  host: redis-verification
  port: 6379
  password: 12345
  db: 0
  protocol: 3
server:
  host: 0.0.0.0
  port: 8080
sql:
  path: /app/sql
jwt:
  secret: super_secret_key_123