name: Deploy Docker on server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v5

        - name: 
          uses: appleboy/ssh-action@v1.2.2
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
                echo "Pulling latest changes from git..."
                cd /opt/project/go-auth-service
                git pull origin main

                echo "Building Docker images..."
                docker compose -f /opt/project/go-auth-service/docker-compose.yml up --build -d backend frontend

                echo "Deployment completed successfully!"